version: '3'

services:

  redis:
      image: redis:latest
      container_name: redis-container
      restart: always
      expose:
        - "6379"
      ports:
        - "6379:6379"
      networks:
        - database_network
        
networks:
  database_network:
